"use strict";
const nameTabs={github:"GitHub",omarchy:"Omarchy",plugins:"плагины",opening:"Начало фразы",development:"Разработка",linux:"Linux"};
const routeTab=location.pathname.slice(1);
const state={tab:nameTabs[routeTab]?routeTab:"disputes",page:0,total:0,size:20,csrf:"",busy:false};
const $=id=>document.getElementById(id);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text,error=false){$("notice").textContent=text;$("notice").className=error?"error":"";}
async function api(path,options={}){const response=await fetch(path,{cache:"no-store",...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"Запрос не выполнен");return data;}
async function status(){const data=await api("/api/status");state.csrf=data.csrf;$("stats").replaceChildren();for(const [value,label]of[[data.unique_terms,"слов и выражений"],[data.observation_rows,"наблюдений"],[data.disputes,"спорных фрагментов"],[data.feedback_count,"твоих решений"]]){const n=node("span");n.append(node("strong",value.toLocaleString("ru-RU")),document.createTextNode(" "+label));$("stats").append(n);}return data;}
function action(label,callback,cls){const b=node("button",label,cls);b.type="button";b.addEventListener("click",callback);return b;}
async function decide(item,kind,decision,value,card){if(card.dataset.saving)return;card.dataset.saving="1";const buttons=[...card.querySelectorAll("button")];buttons.forEach(b=>b.disabled=true);const stamp=card.querySelector(".decision-status");stamp.textContent="Сохраняем…";try{const id=window.crypto?.randomUUID?crypto.randomUUID():"feedback_"+Date.now()+"_"+Math.random().toString(36).slice(2);await api("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":state.csrf},body:JSON.stringify({kind,key:item.key,revision:item.revision,decision,value,request_id:id})});stamp.textContent="Сохранено. Автозамена и обучение не включены.";stamp.className="decision-status saved";notice("Решение записано.");await status();}catch(error){stamp.textContent=error.message;stamp.className="decision-status error";buttons.forEach(b=>b.disabled=false);}finally{delete card.dataset.saving;}}
function customControl(item,kind,card,decision="custom"){ const wrap=node("div",undefined,"custom");const input=node("input");input.type="text";input.maxLength=decision==="sentence_custom"?2048:160;input.placeholder=decision==="sentence_custom"?"Своя полная фраза":"Своё написание";input.setAttribute("aria-label","Своё написание");wrap.append(input,action("Сохранить свой вариант",()=>{if(input.value.trim())void decide(item,kind,decision,input.value.trim(),card);else input.focus();},"secondary"));return wrap;}
function highlighted(text,range){const line=node("p",undefined,"context");if(!range){line.textContent=text;return line;}const [start,end]=range;const chars=Array.from(text);line.append(document.createTextNode(chars.slice(0,start).join("")),node("mark",start===end?"[здесь пропуск]":chars.slice(start,end).join("")),document.createTextNode(chars.slice(end).join("")));return line;}
function disputeCard(item){
  const card=node("article");const alignment=item.alignment||{reliable:false,mode:"sentence",reason:"Отдельные слова не сопоставлены."};
  card.append(node("p",item.hinted?"Проверяющий получил подсказки словаря":"Независимая проверка без словаря","meta"));
  const local=alignment.reliable;
  card.append(node("p",local?"Выделено одно место в двух расшифровках. Аудио — вся запись.":alignment.reason,local?"meta":"alignment-warning"));
  const choices=node("div",undefined,"alternatives");
  for(const [label,fragment,text,range]of[["Основной STT",item.primary,item.context_primary,alignment.primary_range],["Проверяющий",item.teacher,item.context_teacher,alignment.teacher_range]]){
    const wrap=node("div",undefined,"variant");wrap.append(node("p",label,"label"));
    if(local)wrap.append(node("strong",fragment||"Пропуск"));
    wrap.append(highlighted(text||"Полный контекст недоступен",local?range:null));choices.append(wrap);
  }
  card.append(choices);
  if(item.audio_available){const audio=node("audio");audio.controls=true;audio.preload="none";audio.src="/audio/"+encodeURIComponent(item.sample_id);card.append(audio);}else card.append(node("p","Исходная запись недоступна или удалена ротацией.","meta"));
  const actions=node("div",undefined,"actions");const complete=Boolean(item.context_primary&&item.context_teacher);
  if(local){actions.append(action("Этот фрагмент — основной",()=>void decide(item,"dispute","primary","",card)),action("Этот фрагмент — проверяющий",()=>void decide(item,"dispute","teacher","",card)));}
  else if(complete){actions.append(action("Целая фраза — основной",()=>void decide(item,"dispute","sentence_primary","",card)),action("Целая фраза — проверяющий",()=>void decide(item,"dispute","sentence_teacher","",card)));}
  actions.append(action("Пока не знаю",()=>void decide(item,"dispute","skip","",card),"ghost"));card.append(actions);
  if(local||complete)card.append(customControl(item,"dispute",card,local?"custom":"sentence_custom"));
  card.append(node("p",item.decision?"Ранее сохранено: "+item.decision.decision+". Старые решения не изменены.":"Если порядок слов или смысл различается, можно пропустить.","decision-status meta"));return card;
}
function nameCard(item){const card=node("article");card.append(node("p",item.stage==="stt_raw"?"Исходный текст STT до любых замен":item.stage==="teacher_hinted"?"Проверяющий с подсказками — не эталон":"Проверяющий без словаря — не эталон","meta"),node("h2",item.surface),node("p",item.reason,item.label==="ambiguous"?"alignment-warning":"meta"),highlighted(item.text,item.range));if(item.audio_available){const audio=node("audio");audio.controls=true;audio.preload="none";audio.src="/audio/"+encodeURIComponent(item.sample_id);card.append(audio);}else card.append(node("p","Исходная запись уже недоступна. Можно оставить «не уверен».","meta"));const actions=node("div",undefined,"actions");if(item.topic_queue){for(const suggestion of item.suggestions||[])actions.append(action("Имелось в виду: "+suggestion,()=>void decide(item,"name_occurrence","custom",suggestion,card)));actions.append(action("Распознано верно как есть",()=>void decide(item,"name_occurrence","as_heard","",card),"secondary"),action("Не технический термин",()=>void decide(item,"name_occurrence","no","",card),"ghost"),action("Не уверен",()=>void decide(item,"name_occurrence","unsure","",card),"secondary"));}else if(item.canonical==="Смотри"){const surface=item.surface.toLocaleLowerCase("ru-RU");if(surface==="ну")actions.append(action("Это вводное «Ну», не «Смотри»",()=>void decide(item,"name_occurrence","custom","Ну",card)));else if(surface==="смотри"||surface==="смотрите")actions.append(action("Сказано: «"+item.surface+"»",()=>void decide(item,"name_occurrence","custom",item.surface,card)));else actions.append(action("Вместо имени было сказано «Смотри»",()=>void decide(item,"name_occurrence","custom","Смотри",card)));actions.append(action("Исходное слово верно как есть",()=>void decide(item,"name_occurrence","as_heard","",card),"secondary"),action("Не вводное слово",()=>void decide(item,"name_occurrence","no","",card),"ghost"),action("Не уверен",()=>void decide(item,"name_occurrence","unsure","",card),"secondary"));}else actions.append(action("Здесь имелось в виду: "+item.canonical,()=>void decide(item,"name_occurrence","yes","",card)),action("Нет, это другое слово",()=>void decide(item,"name_occurrence","no","",card),"ghost"),action("Не уверен",()=>void decide(item,"name_occurrence","unsure","",card),"secondary"));card.append(actions,customControl(item,"name_occurrence",card),node("p",item.decision?"Сохранено раньше: "+item.decision.decision:"Решение только об этом месте. Глобальное правило замены не создаётся.","decision-status meta"));return card;}
function termCard(item){const card=node("article");card.append(node("h2",item.text),node("p",`${item.occurrences} встреч · ${item.sources} источников`,"meta"));if(item.confirmed)card.append(node("p","Подтверждено как существующее название","confirmed"));else card.append(node("p","Наблюдаемое слово — ещё не подтверждённое название","meta"));const actions=node("div",undefined,"actions");actions.append(action("Да, использую это название",()=>void decide(item,"term","confirm","",card)),action("Ошибка / не нужно",()=>void decide(item,"term","reject","",card),"ghost"),action("Пропустить",()=>void decide(item,"term","skip","",card),"secondary"));card.append(actions,customControl(item,"term",card),node("p",item.decision?"Последнее решение: "+item.decision.decision:"Не нужно подтверждать обычные слова по одному.","decision-status meta"));return card;}
async function load(){if(state.busy){state.reloadPending=true;return;}state.busy=true;notice("Загружаем…");try{const params=new URLSearchParams({q:$("search").value,page:String(state.page)});if(state.tab!=="terms")params.set("pending",$("pending").checked?"1":"0");else params.set("filter",$("term-filter").value);const data=await api("/api/"+state.tab+"?"+params);state.total=data.total;state.size=data.page_size;$("name-summary").hidden=!nameTabs[state.tab];if(nameTabs[state.tab]){$("name-summary").replaceChildren(node("p",`Проверено: ${data.scanned_stt||0} записей STT из ${data.scanned_sources} архивных источников. Кандидаты найдены в ${data.matched_stt_records||0} исходных записях. Очередь «${nameTabs[state.tab]}»: это кандидаты, не автоматические исправления.`,`meta`),node("p","Найденные написания: "+data.variants.map(v=>`${v.surface} (${v.count})`).join(" · "),"context"));}$("results").replaceChildren(...data.items.map(nameTabs[state.tab]?nameCard:state.tab==="disputes"?disputeCard:termCard));if(!data.items.length)$("results").append(node("p","Ничего не найдено. Попробуй другой поиск или покажи записи с решениями.","empty"));$("page-label").textContent=`Страница ${state.page+1} · всего ${data.total}`;$("previous").disabled=state.page===0;$("next").disabled=(state.page+1)*state.size>=state.total;notice("");}catch(error){notice(error.message,true);}finally{state.busy=false;if(state.reloadPending){state.reloadPending=false;void load();}}}
function tab(name){state.tab=name;state.page=0;$("disputes-tab").setAttribute("aria-pressed",String(name==="disputes"));$("terms-tab").setAttribute("aria-pressed",String(name==="terms"));for(const key of Object.keys(nameTabs))$(key+"-tab").setAttribute("aria-pressed",String(name===key));$("pending-control").hidden=name==="terms";$("term-filter-control").hidden=name!=="terms";void load();}
for(const key of Object.keys(nameTabs))$(key+"-tab").onclick=()=>tab(key);$("disputes-tab").onclick=()=>tab("disputes");$("terms-tab").onclick=()=>tab("terms");$("search-form").onsubmit=event=>{event.preventDefault();state.page=0;void load();};$("refresh").onclick=()=>{void status().catch(e=>notice(e.message,true));void load();};$("pending").onchange=()=>{state.page=0;void load();};$("term-filter").onchange=()=>{state.page=0;void load();};$("previous").onclick=()=>{state.page--;void load();};$("next").onclick=()=>{state.page++;void load();};status().then(()=>tab(state.tab)).catch(error=>notice(error.message,true));
