"use strict";
const state={tab:"disputes",page:0,total:0,size:20,csrf:"",busy:false};
const $=id=>document.getElementById(id);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text,error=false){$("notice").textContent=text;$("notice").className=error?"error":"";}
async function api(path,options={}){const response=await fetch(path,{cache:"no-store",...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"Запрос не выполнен");return data;}
async function status(){const data=await api("/api/status");state.csrf=data.csrf;$("stats").replaceChildren();for(const [value,label]of[[data.unique_terms,"слов и выражений"],[data.observation_rows,"наблюдений"],[data.disputes,"спорных фрагментов"],[data.feedback_count,"твоих решений"]]){const n=node("span");n.append(node("strong",value.toLocaleString("ru-RU")),document.createTextNode(" "+label));$("stats").append(n);}return data;}
function action(label,callback,cls){const b=node("button",label,cls);b.type="button";b.addEventListener("click",callback);return b;}
async function decide(item,kind,decision,value,card){if(card.dataset.saving)return;card.dataset.saving="1";const buttons=[...card.querySelectorAll("button")];buttons.forEach(b=>b.disabled=true);const stamp=card.querySelector(".decision-status");stamp.textContent="Сохраняем…";try{const id=window.crypto?.randomUUID?crypto.randomUUID():"feedback_"+Date.now()+"_"+Math.random().toString(36).slice(2);await api("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":state.csrf},body:JSON.stringify({kind,key:item.key,revision:item.revision,decision,value,request_id:id})});stamp.textContent="Сохранено. Автозамена и обучение не включены.";stamp.className="decision-status saved";notice("Решение записано.");await status();}catch(error){stamp.textContent=error.message;stamp.className="decision-status error";buttons.forEach(b=>b.disabled=false);}finally{delete card.dataset.saving;}}
function customControl(item,kind,card){const wrap=node("div",undefined,"custom");const input=node("input");input.type="text";input.maxLength=160;input.placeholder="Своё написание";input.setAttribute("aria-label","Своё написание");wrap.append(input,action("Сохранить свой вариант",()=>{if(input.value.trim())void decide(item,kind,"custom",input.value.trim(),card);else input.focus();},"secondary"));return wrap;}
function disputeCard(item){const card=node("article");card.append(node("p",item.hinted?"Проверяющий получил подсказки словаря":"Независимая проверка без словаря","meta"));const choices=node("div",undefined,"alternatives");for(const [label,text]of[["Основной STT",item.primary||"Пропуск"],["Проверяющий",item.teacher||"Пропуск"]]){const wrap=node("div",undefined,"variant");wrap.append(node("p",label,"label"),node("strong",text));choices.append(wrap);}card.append(choices);if(item.context_primary||item.context_teacher){const details=node("details");details.append(node("summary","Показать целую фразу"),node("p","Основной: "+item.context_primary,"context"),node("p","Проверяющий: "+item.context_teacher,"context"));card.append(details);}if(item.audio_available){const audio=node("audio");audio.controls=true;audio.preload="none";audio.src="/audio/"+encodeURIComponent(item.sample_id);card.append(audio);}else card.append(node("p","Исходная запись недоступна или удалена ротацией.","meta"));const actions=node("div",undefined,"actions");actions.append(action("Верный — основной",()=>void decide(item,"dispute","primary","",card)),action("Верный — проверяющий",()=>void decide(item,"dispute","teacher","",card)),action("Пока не знаю",()=>void decide(item,"dispute","skip","",card),"ghost"));card.append(actions,customControl(item,"dispute",card),node("p",item.decision?"Уже есть решение: "+item.decision.decision:"Выбирай только если уверен. Можно пропустить.","decision-status meta"));return card;}
function termCard(item){const card=node("article");card.append(node("h2",item.text),node("p",`${item.occurrences} встреч · ${item.sources} источников`,"meta"));if(item.confirmed)card.append(node("p","Подтверждено как существующее название","confirmed"));else card.append(node("p","Наблюдаемое слово — ещё не подтверждённое название","meta"));const actions=node("div",undefined,"actions");actions.append(action("Да, использую это название",()=>void decide(item,"term","confirm","",card)),action("Ошибка / не нужно",()=>void decide(item,"term","reject","",card),"ghost"),action("Пропустить",()=>void decide(item,"term","skip","",card),"secondary"));card.append(actions,customControl(item,"term",card),node("p",item.decision?"Последнее решение: "+item.decision.decision:"Не нужно подтверждать обычные слова по одному.","decision-status meta"));return card;}
async function load(){if(state.busy){state.reloadPending=true;return;}state.busy=true;notice("Загружаем…");try{const params=new URLSearchParams({q:$("search").value,page:String(state.page)});if(state.tab==="disputes")params.set("pending",$("pending").checked?"1":"0");else params.set("filter",$("term-filter").value);const data=await api("/api/"+state.tab+"?"+params);state.total=data.total;state.size=data.page_size;$("results").replaceChildren(...data.items.map(state.tab==="disputes"?disputeCard:termCard));if(!data.items.length)$("results").append(node("p","Ничего не найдено. Попробуй другой поиск или покажи записи с решениями.","empty"));$("page-label").textContent=`Страница ${state.page+1} · всего ${data.total}`;$("previous").disabled=state.page===0;$("next").disabled=(state.page+1)*state.size>=state.total;notice("");}catch(error){notice(error.message,true);}finally{state.busy=false;if(state.reloadPending){state.reloadPending=false;void load();}}}
function tab(name){state.tab=name;state.page=0;$("disputes-tab").setAttribute("aria-pressed",String(name==="disputes"));$("terms-tab").setAttribute("aria-pressed",String(name==="terms"));$("pending-control").hidden=name!=="disputes";$("term-filter-control").hidden=name!=="terms";void load();}
$("disputes-tab").onclick=()=>tab("disputes");$("terms-tab").onclick=()=>tab("terms");$("search-form").onsubmit=event=>{event.preventDefault();state.page=0;void load();};$("refresh").onclick=()=>{void status().catch(e=>notice(e.message,true));void load();};$("pending").onchange=()=>{state.page=0;void load();};$("term-filter").onchange=()=>{state.page=0;void load();};$("previous").onclick=()=>{state.page--;void load();};$("next").onclick=()=>{state.page++;void load();};status().then(load).catch(error=>notice(error.message,true));
