[Unit]
Wants=
After=
After=network.target

[Service]
Environment=STT_BACKEND=ultra
Environment=PYTHONPATH=/home/deck/homelab/ultra-upgrade/python-0.2.4
Environment=TRANSCRIBE_LIBRARY=/home/deck/homelab/ultra-upgrade/transcribe-0.2.4/transcribe-native-linux-x86_64-cpu-vulkan/libtranscribe.so
Environment=ULTRA_MODEL_PATH=/home/deck/homelab/ultra-upgrade/models/parakeet-ultra-Q8.gguf
Environment=ULTRA_MODEL_SHA256=283562ac9b513f39244fe23c6632738c167d32731a5f4693319a10ca498550a8
Environment=ULTRA_BACKEND=vulkan
